"use strict";

module.exports = Object.freeze({
  schemaVersion: "seti-standard-full-flow-v3",
  config: {
    seed: "seti-116-standard-flow-v2",
    activePlayerCount: 4,
    aiDifficulty: "weak_start",
    offlineTeacher: true,
    policyVersion: "seti-heuristic-policy-v4",
    opponentIdentity: "seti-heuristic-policy-v4",
  },
  policyProvenance: {
    type: "heuristic",
    version: "seti-heuristic-policy-v4",
    config: {
      difficulty: "weak_start",
      evaluationParameters: { parameterVersion: "seti-probe-goal-v1" },
    },
    configChecksum: "36253d98",
  },
  openingSemanticChoices: [
    { family: "choose_payment", actorPlayerId: "player-white", cardId: "dlc_9.png" },
    { family: "choose_payment", actorPlayerId: "player-blue", cardId: "dlc_2.png" },
    { family: "choose_payment", actorPlayerId: "player-blue", cardId: "b_131.webp" },
    { family: "choose_payment", actorPlayerId: "player-blue", cardId: "dlc_12.png" },
    { family: "choose_payment", actorPlayerId: "player-green", cardId: "b_81.webp" },
    { family: "choose_payment", actorPlayerId: "player-green", cardId: "b_41.webp" },
    { family: "choose_payment", actorPlayerId: "player-brown", cardId: "b_84.webp" },
    { family: "choose_payment", actorPlayerId: "player-brown", cardId: "b_133.webp" },
    { family: "choose_payment", actorPlayerId: "player-brown", cardId: "b_101.webp" },
  ],
  operations: [
    ["choose_payment:4ff87776", 0], ["choose_payment:3766fce9", 0],
    ["choose_payment:0151fcf3", 0], ["choose_payment:63c00c92", 0],
    ["choose_payment:342b1e82", 0], ["choose_payment:0692af73", 0],
    ["choose_payment:67c0a3aa", 3], ["choose_payment:b6c3103a", 3],
    ["choose_payment:5d6ff984", 0], ["launch:c94cda79", 4],
    ["move:5a58dd43", 4], ["choose_payment:31e55dce", 0],
    ["move:5a58dd43", 4], ["choose_payment:31e55dce", 0],
    ["move:5a58dd43", 4], ["choose_payment:31e55dce", 0],
    ["card_corner:4662246c", 0], ["choose_target:3a2b3744", 0],
    ["pass:a1f33c73", 3], ["choose_card:01cec1e6", 0],
    ["end_turn:b2f9b29d", 0], ["launch:a4087d46", 4],
    ["move:340a2fea", 4], ["choose_payment:08ce11f7", 0],
    ["pass:c858282e", 6], ["choose_card:642e6f94", 0],
    ["end_turn:320f2608", 0], ["launch:70d77c1b", 5],
    ["move:f7dd6eeb", 5], ["choose_payment:9938c7f8", 0],
    ["move:f7dd6eeb", 5], ["choose_payment:9938c7f8", 0],
    ["move:f7dd6eeb", 6], ["choose_payment:9938c7f8", 0],
    ["move:f7dd6eeb", 5], ["choose_payment:9938c7f8", 0],
    ["research_tech:58603135", 16], ["pass:ff716055", 7],
    ["choose_card:7635f3e3", 0], ["end_turn:1f65daa3", 0],
    ["launch:c1616852", 4], ["move:76ddf025", 4],
    ["choose_payment:d008d903", 0], ["move:749cfc96", 4],
    ["choose_payment:d008d903", 0],
  ],
  initialSnapshot: {
    turn: [1, 1, 1, "player-white"],
    players: [
      ["player-blue", 6, 5, 2, 4, 2, 5, 0],
      ["player-green", 8, 3, 3, 4, 2, 6, 0],
      ["player-brown", 11, 3, 2, 3, 0, 6, 0],
      ["player-white", 6, 4, 3, 4, 2, 4, 0],
    ],
    publicCards: ["dlc_26.png", "b_59.webp", "b_109.webp"],
    rockets: [
      [1, "player-white", "planets-reference"],
      [2, "player-brown", "planets-reference"],
      [3, "player-blue", "planets-reference"],
      [4, "player-green", "planets-reference"],
    ],
    pending: ["player-white", "player-white", "conditional_choice", 4],
  },
  finalSnapshot: {
    turn: [
      1, 4, 1, "player-brown",
      ["player-white", "player-blue", "player-green"],
      ["player-white", "player-blue", "player-green"],
      false,
    ],
    players: [
      ["player-blue", 6, 9, 2, 6, 2,
        ["dlc_36.png", "b_17.webp", "b_70.webp", "dlc_10.png", "dlc_14.png", "b_28.webp"],
        [], {}, 2, []],
      ["player-green", 10, 3, 3, 0, 2,
        ["b_46.webp", "b_5.webp", "b_60.webp", "b_49.webp", "b_111.webp", "b_29.webp",
          "b_51.webp", "b_62.webp"],
        [], { blue4: true }, 2, []],
      ["player-brown", 11, 2, 1, 4, 0,
        ["b_80.webp", "dlc_21.png", "b_115.webp", "b_118.webp"],
        [], {}, 0, []],
      ["player-white", 6, 5, 1, 5, 2,
        ["dlc_31.png", "dlc_41.png", "b_77.webp", "b_105.webp", "b_139.webp", "dlc_28.png"],
        [], {}, 2, []],
    ],
    cards: {
      public: ["dlc_26.png", "b_59.webp", "b_109.webp"],
      discard: [
        "dlc_9.png", "dlc_2.png", "b_131.webp", "dlc_12.png", "b_81.webp",
        "b_41.webp", "b_84.webp", "b_133.webp", "b_101.webp", "b_113.webp",
      ],
    },
    rockets: [
      [1, "player-white", "planets-reference", null, "venus", "orbit"],
      [2, "player-brown", "planets-reference", null, "saturn", "orbit"],
      [3, "player-blue", "planets-reference", null, "mercury", "orbit"],
      [4, "player-green", "planets-reference", null, "mars", "orbit"],
      [5, "player-white", "solar-board", [5, 1], null, null],
      [6, "player-blue", "solar-board", [1, 2], null, null],
      [7, "player-green", "solar-board", [5, 1], null, null],
      [8, "player-brown", "solar-board", [7, 1], null, null],
    ],
    planets: {
      aomomo: [[], [], []], earth: [[], [], []], jupiter: [[], [], []],
      mars: [["player-green"], [], []], mercury: [["player-blue"], [], []],
      neptune: [[], [], []], saturn: [["player-brown"], [], []],
      uranus: [[], [], []], venus: [["player-white"], [], []],
    },
    data: [
      ["sector-1-a", 1, "player-blue"], ["sector-1-a", 2, "player-blue"],
      ["sector-2-b", 1, "player-green"], ["sector-2-b", 2, "player-green"],
      ["sector-3-b", 1, "player-white"], ["sector-3-b", 2, "player-white"],
    ],
    aliens: {
      slots: [
        ["1", null, false, [false, false, false]],
        ["2", null, false, [false, false, false]],
      ],
      revealed: [false, false, false, false, false, false, false, false],
    },
    authority: [25, "seti-simulation-mulberry32-v1", 1542217152, 1],
    session: [null, "player-brown", null, "turn_action", 40, 45, 45],
  },
  finalCheckpointHash: "d47efca1a9048e7a5a1b52216a1faf518bad2f6a4fa2224ab482a42c3c2ea546",
});
